Repository server-geeks/WebMine, pull requests merged in 2022-10, with the labels that each got.

#4 Added Personal Portfolio - Resolved issues from last time
  PersonalPortfolioSaif/css/skins/color-1.css
  PersonalPortfolioSaif/css/skins/color-2.css
  PersonalPortfolioSaif/css/skins/color-3.css
  PersonalPortfolioSaif/css/skins/color-4.css
  PersonalPortfolioSaif/css/skins/color-5.css
  PersonalPortfolioSaif/css/style-switcher.css
  PersonalPortfolioSaif/css/style.css
  PersonalPortfolioSaif/images/hero.jpeg
  PersonalPortfolioSaif/images/portfolio/portfolio-1.jpg
  PersonalPortfolioSaif/images/portfolio/portfolio-2.jpg
  PersonalPortfolioSaif/images/portfolio/portfolio-3.jpg
  PersonalPortfolioSaif/images/portfolio/portfolio-4.jpg
  PersonalPortfolioSaif/images/portfolio/portfolio-5.jpg
  PersonalPortfolioSaif/images/portfolio/portfolio-6.jpg
  PersonalPortfolioSaif/index.html
  PersonalPortfolioSaif/js/script.js
  PersonalPortfolioSaif/js/style-switcher.js
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#3 A weather forecasting web app
  Weather/Background.jpg
  Weather/app.js
  Weather/index.html
  Weather/style.css
  Weather/unknown.png
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#9 Added Todo List to the project repo
  Todo List/README.md
  Todo List/index.html
  Todo List/project2.webp
  Todo List/script.js
  Todo List/style.css
Labels: hacktoberfest2022, hacktoberfest-accepted

#6 Created Stick Game
  Stick Game/app.js
  Stick Game/index.html
  Stick Game/style.css
  StickGame/readme.md
Labels: hacktoberfest2022, hacktoberfest

#10 Background Generator
  BackgroundGenerator/index.html
  BackgroundGenerator/script.js
  BackgroundGenerator/style.css
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#15 Added VoiceNumberGuesser
  VoiceNumberGuesser/app/initLang.js
  VoiceNumberGuesser/app/sortNumber.js
  VoiceNumberGuesser/app/validation.js
  VoiceNumberGuesser/app/voiceRecognition.js
  VoiceNumberGuesser/index.html
  VoiceNumberGuesser/styles.css
Labels: hacktoberfest2022, hacktoberfest22

#13 Added drum Kit
  DrumKit/README.md
  DrumKit/images/crash.png
  DrumKit/images/kick.png
  DrumKit/images/snare.png
  DrumKit/images/tom1.png
  DrumKit/images/tom2.png
  DrumKit/images/tom3.png
  DrumKit/images/tom4.png
  DrumKit/index.html
  DrumKit/index.js
  DrumKit/sounds/crash.mp3
  DrumKit/sounds/kick-bass.mp3
  DrumKit/sounds/snare.mp3
  DrumKit/sounds/tom-1.mp3
  DrumKit/sounds/tom-2.mp3
  DrumKit/sounds/tom-3.mp3
  DrumKit/sounds/tom-4.mp3
  DrumKit/styles.css
Labels: hacktoberfest2022, hacktoberfest22

#24 Change Color and Shape
  ChangeColorShape/images/gr1.png
  ChangeColorShape/images/gr10.png
  ChangeColorShape/images/gr11.png
  ChangeColorShape/images/gr12.jpg
  ChangeColorShape/images/gr13.jpg
  ChangeColorShape/images/gr2.png
  ChangeColorShape/images/gr3.png
  ChangeColorShape/images/gr4.png
  ChangeColorShape/images/gr5.jpg
  ChangeColorShape/images/gr6.png
  ChangeColorShape/images/gr7.png
  ChangeColorShape/images/gr8.png
  ChangeColorShape/images/gr9.jpg
  ChangeColorShape/index.html
  ChangeColorShape/index.js
  ChangeColorShape/preview.png
  ChangeColorShape/style.css
Labels: hacktoberfest2022, hacktoberfest-accepted

#26 LoginProject
  LoginPage/index.html
  LoginPage/screenshot/1.png
  LoginPage/style.css
Labels: hacktoberfest2022, hacktoberfest-accepted

#30 added stickyElement file
  StickyElement/index.html
  StickyElement/screenshots/Capture1.PNG
  StickyElement/screenshots/Capture2.PNG
  StickyElement/style.css
Labels: hacktoberfest2022, hacktoberfest

#34 Disney hotstar clone
  DisneyHotstarClone/README.md
  DisneyHotstarClone/images/add.png
  DisneyHotstarClone/images/disney.png
  DisneyHotstarClone/images/favicon.ico
  DisneyHotstarClone/images/geographic.png
  DisneyHotstarClone/images/logo.png
  DisneyHotstarClone/images/marvel.png
  DisneyHotstarClone/images/nxt.png
  DisneyHotstarClone/images/pixar.png
  DisneyHotstarClone/images/play.png
  DisneyHotstarClone/images/poster 1.png
  DisneyHotstarClone/images/poster 10.png
  DisneyHotstarClone/images/poster 11.png
  DisneyHotstarClone/images/poster 12.png
  DisneyHotstarClone/images/poster 2.png
  DisneyHotstarClone/images/poster 3.png
  DisneyHotstarClone/images/poster 4.png
  DisneyHotstarClone/images/poster 5.png
  DisneyHotstarClone/images/poster 6.png
  DisneyHotstarClone/images/poster 7.png
  DisneyHotstarClone/images/poster 8.png
  DisneyHotstarClone/images/poster 9.png
  DisneyHotstarClone/images/pre.png
  DisneyHotstarClone/images/slider1.png
  DisneyHotstarClone/images/slider2.png
  DisneyHotstarClone/images/slider3.png
  DisneyHotstarClone/images/slider4.png
  DisneyHotstarClone/images/slider5.png
  DisneyHotstarClone/images/star-wars.png
  DisneyHotstarClone/index.html
  DisneyHotstarClone/index.js
  DisneyHotstarClone/styles.css
  DisneyHotstarClone/videos/disney.mp4
  DisneyHotstarClone/videos/geographic.mp4
  DisneyHotstarClone/videos/marvel.mp4
  DisneyHotstarClone/videos/pixar.mp4
  DisneyHotstarClone/videos/star-war.mp4
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#37 train animation by html and css
  TinDog/.DS_Store
  TinDog/.vscode/settings.json
  TinDog/boostrap.txt
  TinDog/css/.DS_Store
  TinDog/css/styles.css
  TinDog/images/.DS_Store
  TinDog/images/TechCrunch.png
  TinDog/images/bizinsider.png
  TinDog/images/dog-img.jpg
  TinDog/images/iphone6.png
  TinDog/images/lady-img.jpg
  TinDog/images/mashable.png
  TinDog/images/tnw.png
  TinDog/index.html
Labels: hacktoberfest2022, hacktoberfest, changes-requested

#44 Add Contributors section in readme.md
  README.md
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#20 Website Sabino Constructor store
  SabinoConstructor/empresa.html
  SabinoConstructor/fornecedores.html
  SabinoConstructor/images/layout.cdr
  SabinoConstructor/images/layout.jpg
  SabinoConstructor/images/layout_01.jpg
  SabinoConstructor/images/layout_02.jpg
  SabinoConstructor/images/layout_03.jpg
  SabinoConstructor/images/layout_04.jpg
  SabinoConstructor/images/layout_05.jpg
  SabinoConstructor/images/layout_06.jpg
  SabinoConstructor/images/layout_07.jpg
  SabinoConstructor/images/layout_08.jpg
  SabinoConstructor/images/layout_09.jpg
  SabinoConstructor/images/layout_10.jpg
  SabinoConstructor/images/layout_11.jpg
  SabinoConstructor/images/rodape_02.jpg
  SabinoConstructor/images/rodape_03.jpg
  SabinoConstructor/images/rodape_04.jpg
  SabinoConstructor/img add/photo.jpg
  SabinoConstructor/img add/produto01.png
  SabinoConstructor/img add/produto02.png
  SabinoConstructor/index.html
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#46 added Jarvis
  Jarvis/index.html
  Jarvis/ironman-feature.gif
  Jarvis/jarvis-iron-man.gif
  Jarvis/script.js
  Jarvis/style.css
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#41 add blackjack game
  BlackJackGame/bjindex.css
  BlackJackGame/bjindex.html
  BlackJackGame/bjindex.js
  BlackJackGame/screenshort/backjackgamedefaultpage.png
  BlackJackGame/screenshort/cardpage.png
  BlackJackGame/screenshort/winpage.png
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#48 Windows 11 clone added
  Windows11Clone/css/style.css
  Windows11Clone/favicon/android-chrome-192x192.png
  Windows11Clone/favicon/android-chrome-512x512.png
  Windows11Clone/favicon/apple-touch-icon.png
  Windows11Clone/favicon/favicon-16x16.png
  Windows11Clone/favicon/favicon-32x32.png
  Windows11Clone/favicon/favicon.ico
  Windows11Clone/favicon/site.webmanifest
  Windows11Clone/img/bg.jpeg
  Windows11Clone/img/bg2.jpg
  Windows11Clone/img/chromeicon.png
  Windows11Clone/img/edgeicon.png
  Windows11Clone/img/favicon.ico
  Windows11Clone/img/recyclebinicon.png
  Windows11Clone/img/startmenu.PNG
  Windows11Clone/img/taskbar.PNG
  Windows11Clone/img/taskbarright.PNG
  Windows11Clone/index.html
  Windows11Clone/js/script.js
  Windows11Clone/video.webm
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#47 Adding chat app
  ChatApp/package-lock.json
  ChatApp/package.json
  ChatApp/public/chat.html
  ChatApp/public/css/styles.css
  ChatApp/public/css/styles.min.css
  ChatApp/public/img/favicon.png
  ChatApp/public/index.html
  ChatApp/public/js/chat.js
  ChatApp/src/index.js
  ChatApp/src/utils/messages.js
  ChatApp/src/utils/users.js
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#49 Add files via upload
  LandingPage/agency-3.jpg
  LandingPage/contactus.css
  LandingPage/contactus.html
  LandingPage/home.css
  LandingPage/home.html
  LandingPage/index.html
  LandingPage/stylesheet.css
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#52 ExpenseTracker
  ExpenseTracker/README.md
  ExpenseTracker/Screenshots/1.png
  ExpenseTracker/Screenshots/2.png
  ExpenseTracker/Screenshots/3.png
  ExpenseTracker/package-lock.json
  ExpenseTracker/package.json
  ExpenseTracker/public/index.html
  ExpenseTracker/public/manifest.json
  ExpenseTracker/public/robots.txt
  ExpenseTracker/src/App.js
  ExpenseTracker/src/components/Chart/Chart.css
  ExpenseTracker/src/components/Chart/Chart.js
  ExpenseTracker/src/components/Chart/ChartBar.css
  ExpenseTracker/src/components/Chart/ChartBar.js
  ExpenseTracker/src/components/Expense/ExpenseDate.css
  ExpenseTracker/src/components/Expense/ExpenseDate.js
  ExpenseTracker/src/components/Expense/ExpenseDetails.js
  ExpenseTracker/src/components/Expense/ExpenseItem.js
  ExpenseTracker/src/components/Expense/ExpenseItemCss.css
  ExpenseTracker/src/components/Expense/Expenses.css
  ExpenseTracker/src/components/Expense/Expenses.js
  ExpenseTracker/src/components/Expense/ExpensesChart.js
  ExpenseTracker/src/components/Expense/ExpensesFilter.css
  ExpenseTracker/src/components/Expense/ExpensesFilter.js
  ExpenseTracker/src/components/NewExpense/ExpenseForm.css
  ExpenseTracker/src/components/NewExpense/ExpenseForm.js
  ExpenseTracker/src/components/NewExpense/NewExpense.css
  ExpenseTracker/src/components/NewExpense/NewExpense.js
  ExpenseTracker/src/components/UI/Card.css
  ExpenseTracker/src/components/UI/Card.js
  ExpenseTracker/src/index.css
  ExpenseTracker/src/index.js
Labels: hacktoberfest2022, hacktoberfest

#14 CharacterCounter
  8_Character_Counter/index.html
  8_Character_Counter/index.js
  8_Character_Counter/style.css
  ButtonEffect/index.html
  ButtonEffect/index.js
  ButtonEffect/style.css
  CharacterCounter/index.html
  CharacterCounter/index.js
  CharacterCounter/style.css
  SimpleFrontend/Images/apj.jpg
  SimpleFrontend/index.html
  SimpleFrontend/style.css
Labels: hacktoberfest2022, hacktoberfest-accepted

#54 WeddingWebsite
  WeddingWebsite/images/banquet.jpg
  WeddingWebsite/images/birthdayevent.jpg
  WeddingWebsite/images/card-bg.png
  WeddingWebsite/images/catering.jpg
  WeddingWebsite/images/chrityevent.jpg
  WeddingWebsite/images/confrencevent.jpg
  WeddingWebsite/images/decoration.jpg
  WeddingWebsite/images/divider.png
  WeddingWebsite/images/dj.jpg
  WeddingWebsite/images/florist.jpg
  WeddingWebsite/images/header-img.png
  WeddingWebsite/images/home-bg.jpg
  WeddingWebsite/images/img6.jpg
  WeddingWebsite/images/pexel1.jpg
  WeddingWebsite/images/photographer.jpg
  WeddingWebsite/images/team-1.png
  WeddingWebsite/images/team-2.png
  WeddingWebsite/images/team-3.png
  WeddingWebsite/images/weddingevent.jpg
  WeddingWebsite/index.html
  WeddingWebsite/ss1.PNG
  WeddingWebsite/ss2.PNG
  WeddingWebsite/style.css
Labels: hacktoberfest2022, hacktoberfest, changes-requested

#57 added zomato-clone website (frontend) and a screenshot of the live site.
  ZomatoClone/index.html
  ZomatoClone/screenshot zomato clone.png
  ZomatoClone/style.css
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#59 Blog Site Added
  BlogSite/package-lock.json
  BlogSite/package.json
  BlogSite/public/css/Icon.png
  BlogSite/public/css/JS.js
  BlogSite/public/css/style.css
  BlogSite/script.js
  BlogSite/views/about.ejs
  BlogSite/views/compose.ejs
  BlogSite/views/contact.ejs
  BlogSite/views/home.ejs
  BlogSite/views/partials/footer.ejs
  BlogSite/views/partials/header.ejs
  BlogSite/views/post.ejs
  BlogSite/views/riverr.ejs
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#61 Added Url Shortner
  UrlShortner/.gitignore
  UrlShortner/README.md
  UrlShortner/models/shortUrls.js
  UrlShortner/package-lock.json
  UrlShortner/package.json
  UrlShortner/public/favicon.ico
  UrlShortner/public/favicon.png
  UrlShortner/public/icons/icon-192x192.png
  UrlShortner/public/icons/icon-256x256.png
  UrlShortner/public/icons/icon-384x384.png
  UrlShortner/public/icons/icon-512x512.png
  UrlShortner/public/manifest.json
  UrlShortner/public/sw.js
  UrlShortner/public/views/all.ejs
  UrlShortner/public/views/index.ejs
  UrlShortner/public/views/success.ejs
  UrlShortner/server.js
Labels: hacktoberfest2022, hacktoberfest-accepted
